-- Seed data for development and demos

-- Loyalty levels (spec 2.2.1)
INSERT INTO NIVO_LOJALNOSTI (ID_NIVOJA, KODA, NAZIV_SL, NAZIV_EN, OPIS) VALUES (seq_nivo.NEXTVAL, 'OSNOVNI', 'Osnovni', 'Basic', 'Začetni nivo ob registraciji');
INSERT INTO NIVO_LOJALNOSTI (ID_NIVOJA, KODA, NAZIV_SL, NAZIV_EN, OPIS) VALUES (seq_nivo.NEXTVAL, 'BRONASTI', 'Bronasti', 'Bronze', 'Znižan nivo');
INSERT INTO NIVO_LOJALNOSTI (ID_NIVOJA, KODA, NAZIV_SL, NAZIV_EN, OPIS) VALUES (seq_nivo.NEXTVAL, 'SREBRNI', 'Srebrni', 'Silver', 'Srednji nivo');
INSERT INTO NIVO_LOJALNOSTI (ID_NIVOJA, KODA, NAZIV_SL, NAZIV_EN, OPIS) VALUES (seq_nivo.NEXTVAL, 'ZLATI', 'Zlati', 'Gold', 'Najvišji nivo');

-- Default points rules (spec 2.2.3) - bracket: do 200, 200-1000, nad 1000
-- Osnovni
INSERT INTO PRAVILO_TOCKOVANJA (ID_PRAVILA, ID_NIVOJA, ZNESEK_OD, ZNESEK_DO, TOCKE)
SELECT seq_pravilo_tocke.NEXTVAL, ID_NIVOJA, 0, 200, 5 FROM NIVO_LOJALNOSTI WHERE KODA = 'OSNOVNI';
INSERT INTO PRAVILO_TOCKOVANJA (ID_PRAVILA, ID_NIVOJA, ZNESEK_OD, ZNESEK_DO, TOCKE)
SELECT seq_pravilo_tocke.NEXTVAL, ID_NIVOJA, 200.01, 1000, 10 FROM NIVO_LOJALNOSTI WHERE KODA = 'OSNOVNI';
INSERT INTO PRAVILO_TOCKOVANJA (ID_PRAVILA, ID_NIVOJA, ZNESEK_OD, ZNESEK_DO, TOCKE)
SELECT seq_pravilo_tocke.NEXTVAL, ID_NIVOJA, 1000.01, NULL, 20 FROM NIVO_LOJALNOSTI WHERE KODA = 'OSNOVNI';
-- Bronasti
INSERT INTO PRAVILO_TOCKOVANJA (ID_PRAVILA, ID_NIVOJA, ZNESEK_OD, ZNESEK_DO, TOCKE)
SELECT seq_pravilo_tocke.NEXTVAL, ID_NIVOJA, 0, 200, 0 FROM NIVO_LOJALNOSTI WHERE KODA = 'BRONASTI';
INSERT INTO PRAVILO_TOCKOVANJA (ID_PRAVILA, ID_NIVOJA, ZNESEK_OD, ZNESEK_DO, TOCKE)
SELECT seq_pravilo_tocke.NEXTVAL, ID_NIVOJA, 200.01, 1000, 5 FROM NIVO_LOJALNOSTI WHERE KODA = 'BRONASTI';
INSERT INTO PRAVILO_TOCKOVANJA (ID_PRAVILA, ID_NIVOJA, ZNESEK_OD, ZNESEK_DO, TOCKE)
SELECT seq_pravilo_tocke.NEXTVAL, ID_NIVOJA, 1000.01, NULL, 10 FROM NIVO_LOJALNOSTI WHERE KODA = 'BRONASTI';
-- Srebrni
INSERT INTO PRAVILO_TOCKOVANJA (ID_PRAVILA, ID_NIVOJA, ZNESEK_OD, ZNESEK_DO, TOCKE)
SELECT seq_pravilo_tocke.NEXTVAL, ID_NIVOJA, 0, 200, 7.5 FROM NIVO_LOJALNOSTI WHERE KODA = 'SREBRNI';
INSERT INTO PRAVILO_TOCKOVANJA (ID_PRAVILA, ID_NIVOJA, ZNESEK_OD, ZNESEK_DO, TOCKE)
SELECT seq_pravilo_tocke.NEXTVAL, ID_NIVOJA, 200.01, 1000, 15 FROM NIVO_LOJALNOSTI WHERE KODA = 'SREBRNI';
INSERT INTO PRAVILO_TOCKOVANJA (ID_PRAVILA, ID_NIVOJA, ZNESEK_OD, ZNESEK_DO, TOCKE)
SELECT seq_pravilo_tocke.NEXTVAL, ID_NIVOJA, 1000.01, NULL, 30 FROM NIVO_LOJALNOSTI WHERE KODA = 'SREBRNI';
-- Zlati
INSERT INTO PRAVILO_TOCKOVANJA (ID_PRAVILA, ID_NIVOJA, ZNESEK_OD, ZNESEK_DO, TOCKE)
SELECT seq_pravilo_tocke.NEXTVAL, ID_NIVOJA, 0, 200, 10 FROM NIVO_LOJALNOSTI WHERE KODA = 'ZLATI';
INSERT INTO PRAVILO_TOCKOVANJA (ID_PRAVILA, ID_NIVOJA, ZNESEK_OD, ZNESEK_DO, TOCKE)
SELECT seq_pravilo_tocke.NEXTVAL, ID_NIVOJA, 200.01, 1000, 20 FROM NIVO_LOJALNOSTI WHERE KODA = 'ZLATI';
INSERT INTO PRAVILO_TOCKOVANJA (ID_PRAVILA, ID_NIVOJA, ZNESEK_OD, ZNESEK_DO, TOCKE)
SELECT seq_pravilo_tocke.NEXTVAL, ID_NIVOJA, 1000.01, NULL, 40 FROM NIVO_LOJALNOSTI WHERE KODA = 'ZLATI';

-- Status rules metadata (configurable thresholds - spec defaults)
INSERT INTO PRAVILO_STATUSA (ID_PRAVILA, TIP_PRAVILA, POGOJ_OPIS, PRAG_ZNESEK, STEVILO_MESECEV)
VALUES (seq_pravilo_status.NEXTVAL, 'UPGRADE_SILVER', 'Prvič nakupi > prag v obdobju', 499, 1);
INSERT INTO PRAVILO_STATUSA (ID_PRAVILA, TIP_PRAVILA, POGOJ_OPIS, PRAG_ZNESEK, STEVILO_MESECEV)
VALUES (seq_pravilo_status.NEXTVAL, 'UPGRADE_GOLD', 'Število obdobij z nakupi > prag', 500, 3);
INSERT INTO PRAVILO_STATUSA (ID_PRAVILA, TIP_PRAVILA, POGOJ_OPIS, PRAG_ZNESEK, STEVILO_MESECEV)
VALUES (seq_pravilo_status.NEXTVAL, 'MAINTAIN_SILVER', 'Minimalni mesečni nakupi za ohranitev srebrnega', 200, 1);
INSERT INTO PRAVILO_STATUSA (ID_PRAVILA, TIP_PRAVILA, POGOJ_OPIS, PRAG_ZNESEK, STEVILO_MESECEV)
VALUES (seq_pravilo_status.NEXTVAL, 'MAINTAIN_GOLD', 'Minimalni mesečni nakupi za ohranitev zlatega', 500, 1);
INSERT INTO PRAVILO_STATUSA (ID_PRAVILA, TIP_PRAVILA, POGOJ_OPIS, PRAG_ZNESEK, STEVILO_MESECEV)
VALUES (seq_pravilo_status.NEXTVAL, 'DOWNGRADE_SILVER', 'Zaporedna meseca pod pragom', 200, 2);
INSERT INTO PRAVILO_STATUSA (ID_PRAVILA, TIP_PRAVILA, POGOJ_OPIS, PRAG_ZNESEK, STEVILO_MESECEV)
VALUES (seq_pravilo_status.NEXTVAL, 'RECOVER_BRONZE', 'Zaporedna meseca nad pragom', 200, 2);
INSERT INTO PRAVILO_STATUSA (ID_PRAVILA, TIP_PRAVILA, POGOJ_OPIS, PRAG_ZNESEK, STEVILO_MESECEV)
VALUES (seq_pravilo_status.NEXTVAL, 'RESET_BASIC', 'Nakupi pod pragom v obdobju (bronasti)', 50, 1);

-- Reward categories
INSERT INTO KATEGORIJA_NAGRADE (ID_KATEGORIJE, NAZIV_SL, NAZIV_EN) VALUES (seq_kategorija.NEXTVAL, 'Darilne kartice', 'Gift cards');
INSERT INTO KATEGORIJA_NAGRADE (ID_KATEGORIJE, NAZIV_SL, NAZIV_EN) VALUES (seq_kategorija.NEXTVAL, 'Popusti', 'Discounts');
INSERT INTO KATEGORIJA_NAGRADE (ID_KATEGORIJE, NAZIV_SL, NAZIV_EN) VALUES (seq_kategorija.NEXTVAL, 'Izkušnje', 'Experiences');

INSERT INTO NAGRADA (ID_NAGRADE, ID_KATEGORIJE, NAZIV_SL, NAZIV_EN, OPIS_SL, OPIS_EN, VREDNOST_V_TOCKAH, ZALOGA, AKTIVNA)
SELECT seq_nagrada.NEXTVAL, ID_KATEGORIJE, 'Darilna kartica 10 EUR', '10 EUR Gift Card',
       'Uporabna v vseh trgovinah Maestro', 'Valid at all Maestro stores', 500, 100, 'Y'
FROM KATEGORIJA_NAGRADE WHERE NAZIV_EN = 'Gift cards';

INSERT INTO NAGRADA (ID_NAGRADE, ID_KATEGORIJE, NAZIV_SL, NAZIV_EN, OPIS_SL, OPIS_EN, VREDNOST_V_TOCKAH, ZALOGA, AKTIVNA)
SELECT seq_nagrada.NEXTVAL, ID_KATEGORIJE, 'Brezplačna dostava', 'Free Delivery',
       'Enkratna brezplačna dostava', 'One-time free delivery', 200, 500, 'Y'
FROM KATEGORIJA_NAGRADE WHERE NAZIV_EN = 'Discounts';

INSERT INTO NAGRADA (ID_NAGRADE, ID_KATEGORIJE, NAZIV_SL, NAZIV_EN, OPIS_SL, OPIS_EN, VREDNOST_V_TOCKAH, ZALOGA, AKTIVNA)
SELECT seq_nagrada.NEXTVAL, ID_KATEGORIJE, 'VIP dogodek', 'VIP Event Access',
       'Vstopnica za ekskluzivni dogodek', 'Ticket to exclusive event', 2000, 20, 'Y'
FROM KATEGORIJA_NAGRADE WHERE NAZIV_EN = 'Experiences';

COMMIT;
