-- Maestro Loyalty Program - Oracle Database Schema
-- Spec v1.5 - Mattia Lauzana

-- Sequences
CREATE SEQUENCE seq_clan START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE seq_kartica START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE seq_racun START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE seq_obvestilo START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE seq_nakup START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE seq_obdobje START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE seq_status START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE seq_nivo START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE seq_tocke START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE seq_pravilo_status START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE seq_pravilo_tocke START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE seq_uveljavitev START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE seq_nagrada START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE seq_kategorija START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE seq_revizija START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE seq_email_ver START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE seq_reset_gesla START WITH 1 INCREMENT BY 1 NOCACHE;

-- Membership
CREATE TABLE CLAN (
    ID_CLANA            NUMBER PRIMARY KEY,
    IME                 VARCHAR2(100) NOT NULL,
    PRIIMEK             VARCHAR2(100) NOT NULL,
    EMAIL               VARCHAR2(255) NOT NULL,
    NASLOV              VARCHAR2(500),
    DATUM_REGISTRACIJE  TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    AKTIVEN             CHAR(1) DEFAULT 'Y' NOT NULL CHECK (AKTIVEN IN ('Y', 'N')),
    MARKETING_SOGLASJE  CHAR(1) DEFAULT 'N' NOT NULL CHECK (MARKETING_SOGLASJE IN ('Y', 'N')),
    CONSTRAINT uq_clan_email UNIQUE (EMAIL)
);

CREATE TABLE KARTICA_LOJALNOSTI (
    ID_KARTICE          NUMBER PRIMARY KEY,
    ID_CLANA            NUMBER NOT NULL REFERENCES CLAN(ID_CLANA),
    STEVILKA_KARTICE    VARCHAR2(32) NOT NULL,
    DATUM_IZDAJE        TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    STATUS_POSILJANJA   VARCHAR2(20) DEFAULT 'PENDING' NOT NULL
        CHECK (STATUS_POSILJANJA IN ('PENDING', 'SENT', 'DELIVERED')),
    CONSTRAINT uq_kartica_stevilka UNIQUE (STEVILKA_KARTICE)
);

CREATE TABLE UPORABNISK_RACUN (
    ID_RACUNA           NUMBER PRIMARY KEY,
    ID_CLANA            NUMBER REFERENCES CLAN(ID_CLANA),
    UPORABNISKO_IME     VARCHAR2(255) NOT NULL,
    GESLO_HASH          VARCHAR2(255) NOT NULL,
    VLOGA               VARCHAR2(20) NOT NULL CHECK (VLOGA IN ('CLAN', 'ADMIN')),
    EMAIL_VERIFICIRAN   CHAR(1) DEFAULT 'N' NOT NULL CHECK (EMAIL_VERIFICIRAN IN ('Y', 'N')),
    ZADNJA_PRIJAVA      TIMESTAMP,
    AKTIVEN             CHAR(1) DEFAULT 'Y' NOT NULL CHECK (AKTIVEN IN ('Y', 'N')),
    CONSTRAINT uq_racun_uporabnisko UNIQUE (UPORABNISKO_IME),
    CONSTRAINT chk_racun_clan CHECK (
        (VLOGA = 'CLAN' AND ID_CLANA IS NOT NULL) OR
        (VLOGA = 'ADMIN' AND ID_CLANA IS NULL)
    )
);

CREATE TABLE EMAIL_VERIFIKACIJA (
    ID                  NUMBER PRIMARY KEY,
    ID_RACUNA           NUMBER NOT NULL REFERENCES UPORABNISK_RACUN(ID_RACUNA),
    TOKEN               VARCHAR2(64) NOT NULL,
    POTEK               TIMESTAMP NOT NULL,
    UPORABLJEN          CHAR(1) DEFAULT 'N' NOT NULL CHECK (UPORABLJEN IN ('Y', 'N')),
    CONSTRAINT uq_email_ver_token UNIQUE (TOKEN)
);

CREATE TABLE PONASTAVITEV_GESLA (
    ID                  NUMBER PRIMARY KEY,
    ID_RACUNA           NUMBER NOT NULL REFERENCES UPORABNISK_RACUN(ID_RACUNA),
    TOKEN               VARCHAR2(64) NOT NULL,
    POTEK               TIMESTAMP NOT NULL,
    UPORABLJEN          CHAR(1) DEFAULT 'N' NOT NULL CHECK (UPORABLJEN IN ('Y', 'N')),
    CONSTRAINT uq_reset_gesla_token UNIQUE (TOKEN)
);

-- Notifications
CREATE TABLE OBVESTILO (
    ID_OBVESTILA        NUMBER PRIMARY KEY,
    ID_CLANA            NUMBER NOT NULL REFERENCES CLAN(ID_CLANA),
    TIP                 VARCHAR2(50) NOT NULL,
    VSEBINA_SL          CLOB,
    VSEBINA_EN          CLOB,
    DATUM_POSLANJA      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    STATUS              VARCHAR2(20) DEFAULT 'SENT' NOT NULL
);

-- Purchases
CREATE TABLE OBRACUNSKO_OBDOBJE (
    ID_OBDOBJA          NUMBER PRIMARY KEY,
    MESEC               NUMBER(2) NOT NULL CHECK (MESEC BETWEEN 1 AND 12),
    LETO                NUMBER(4) NOT NULL,
    DATUM_UVOZA         TIMESTAMP,
    STATUS_UVOZA        VARCHAR2(20) DEFAULT 'OPEN' NOT NULL
        CHECK (STATUS_UVOZA IN ('OPEN', 'PROCESSING', 'CLOSED')),
    STEVILO_UVOZENIH    NUMBER DEFAULT 0,
    NAPAKE_UVOZA        VARCHAR2(4000),
    CONSTRAINT uq_obdobje UNIQUE (MESEC, LETO)
);

CREATE TABLE NAKUP (
    ID_NAKUPA           NUMBER PRIMARY KEY,
    ID_CLANA            NUMBER NOT NULL REFERENCES CLAN(ID_CLANA),
    ID_OBDOBJA          NUMBER NOT NULL REFERENCES OBRACUNSKO_OBDOBJE(ID_OBDOBJA),
    ZNESEK              NUMBER(12, 2) NOT NULL,
    DATUM_UVOZA         TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

-- Statuses and points
CREATE TABLE NIVO_LOJALNOSTI (
    ID_NIVOJA           NUMBER PRIMARY KEY,
    KODA                VARCHAR2(20) NOT NULL,
    NAZIV_SL            VARCHAR2(50) NOT NULL,
    NAZIV_EN            VARCHAR2(50) NOT NULL,
    OPIS                VARCHAR2(500),
    CONSTRAINT uq_nivo_koda UNIQUE (KODA)
);

CREATE TABLE STATUS_CLANA (
    ID_STATUSA          NUMBER PRIMARY KEY,
    ID_CLANA            NUMBER NOT NULL REFERENCES CLAN(ID_CLANA),
    ID_NIVOJA           NUMBER NOT NULL REFERENCES NIVO_LOJALNOSTI(ID_NIVOJA),
    ID_OBDOBJA          NUMBER REFERENCES OBRACUNSKO_OBDOBJE(ID_OBDOBJA),
    DATUM_OD            TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    DATUM_DO            TIMESTAMP,
    RAZLOG_SPREMEMBE    VARCHAR2(500),
    TRENUTNI            CHAR(1) DEFAULT 'Y' NOT NULL CHECK (TRENUTNI IN ('Y', 'N'))
);

CREATE TABLE TOCKE_TRANSAKCIJA (
    ID_TRANSAKCIJE      NUMBER PRIMARY KEY,
    ID_CLANA            NUMBER NOT NULL REFERENCES CLAN(ID_CLANA),
    ID_OBDOBJA          NUMBER REFERENCES OBRACUNSKO_OBDOBJE(ID_OBDOBJA),
    DATUM               TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    STEVILO_TOCK        NUMBER(10, 2) NOT NULL,
    TIP                 VARCHAR2(30) NOT NULL,
    OPIS                VARCHAR2(500)
);

-- Configurable rules
CREATE TABLE PRAVILO_STATUSA (
    ID_PRAVILA          NUMBER PRIMARY KEY,
    ID_NIVOJA_CILJ      NUMBER REFERENCES NIVO_LOJALNOSTI(ID_NIVOJA),
    TIP_PRAVILA         VARCHAR2(50) NOT NULL,
    POGOJ_OPIS          VARCHAR2(500),
    PRAG_ZNESEK         NUMBER(12, 2),
    STEVILO_MESECEV     NUMBER(3),
    DATUM_VELJAVNOSTI_OD DATE DEFAULT SYSDATE NOT NULL,
    DATUM_VELJAVNOSTI_DO DATE,
    AKTIVNO             CHAR(1) DEFAULT 'Y' NOT NULL CHECK (AKTIVNO IN ('Y', 'N'))
);

CREATE TABLE PRAVILO_TOCKOVANJA (
    ID_PRAVILA          NUMBER PRIMARY KEY,
    ID_NIVOJA           NUMBER NOT NULL REFERENCES NIVO_LOJALNOSTI(ID_NIVOJA),
    ZNESEK_OD           NUMBER(12, 2) NOT NULL,
    ZNESEK_DO           NUMBER(12, 2),
    TOCKE               NUMBER(10, 2) NOT NULL,
    DATUM_VELJAVNOSTI_OD DATE DEFAULT SYSDATE NOT NULL,
    DATUM_VELJAVNOSTI_DO DATE,
    AKTIVNO             CHAR(1) DEFAULT 'Y' NOT NULL CHECK (AKTIVNO IN ('Y', 'N'))
);

-- Rewards
CREATE TABLE KATEGORIJA_NAGRADE (
    ID_KATEGORIJE       NUMBER PRIMARY KEY,
    NAZIV_SL            VARCHAR2(100) NOT NULL,
    NAZIV_EN            VARCHAR2(100) NOT NULL
);

CREATE TABLE NAGRADA (
    ID_NAGRADE          NUMBER PRIMARY KEY,
    ID_KATEGORIJE       NUMBER REFERENCES KATEGORIJA_NAGRADE(ID_KATEGORIJE),
    NAZIV_SL            VARCHAR2(200) NOT NULL,
    NAZIV_EN            VARCHAR2(200) NOT NULL,
    OPIS_SL             VARCHAR2(1000),
    OPIS_EN             VARCHAR2(1000),
    VREDNOST_V_TOCKAH   NUMBER(10) NOT NULL,
    ZALOGA              NUMBER DEFAULT 0 NOT NULL,
    AKTIVNA             CHAR(1) DEFAULT 'Y' NOT NULL CHECK (AKTIVNA IN ('Y', 'N'))
);

CREATE TABLE UVELJAVITEV_NAGRADE (
    ID_UVELJAVITVE      NUMBER PRIMARY KEY,
    ID_CLANA            NUMBER NOT NULL REFERENCES CLAN(ID_CLANA),
    ID_NAGRADE          NUMBER NOT NULL REFERENCES NAGRADA(ID_NAGRADE),
    ID_TRANSAKCIJE      NUMBER REFERENCES TOCKE_TRANSAKCIJA(ID_TRANSAKCIJE),
    DATUM               TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    PORABLJENE_TOCKE    NUMBER(10) NOT NULL,
    STATUS              VARCHAR2(20) DEFAULT 'COMPLETED' NOT NULL
);

-- Audit trail (NZ-12)
CREATE TABLE REVIZIJSKI_DNEVNIK (
    ID                  NUMBER PRIMARY KEY,
    CAS_DOGODKA         TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    ID_RACUNA           NUMBER REFERENCES UPORABNISK_RACUN(ID_RACUNA),
    TIP_DOGODKA         VARCHAR2(50) NOT NULL,
    ENTITETA            VARCHAR2(100),
    ID_ENTITETE         NUMBER,
    PODROBNOSTI         VARCHAR2(2000),
    IP_NASLOV           VARCHAR2(45)
);

-- Indexes
CREATE INDEX idx_nakup_clan ON NAKUP(ID_CLANA);
CREATE INDEX idx_nakup_obdobje ON NAKUP(ID_OBDOBJA);
CREATE INDEX idx_status_clan_trenutni ON STATUS_CLANA(ID_CLANA, TRENUTNI);
CREATE INDEX idx_tocke_clan ON TOCKE_TRANSAKCIJA(ID_CLANA);
CREATE INDEX idx_obvestilo_clan ON OBVESTILO(ID_CLANA);
CREATE INDEX idx_revizija_cas ON REVIZIJSKI_DNEVNIK(CAS_DOGODKA);
